XYZ.WebPage/XYZ.Client/Controllers/BasketController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using XYZ.Business.Abstraction;
using XYZ.Business.Implamentation;
using XYZ.Client.Helper.Abstraction;
using XYZ.Client.Helper.Implamentation;
using XYZ.Entities;
using XYZ.Repository.Implamentation;

namespace XYZ.Client.Controllers
{
    [LogInFilter]
    public class BasketController : Controller
    {
        private readonly IBasketManager _basketManager;
  
        private readonly ISessionHelper _sessionHelper;

        public BasketController()
        {
            _basketManager = DependencyInjectionModule.Resolve<IBasketManager>();
            _sessionHelper = DependencyInjectionModule.Resolve<ISessionHelper>();
        }

        [HttpGet]
        public ActionResult MyBasket()
        {

            Basket basket;
            Customer customer = _sessionHelper.Get<Customer>();

            if (_basketManager.BasketController(customer.CustomerId))
            {
               basket = _basketManager.GetBasket(customer.CustomerId);
                return View(basket);
            }
            else
            {
                return View("ShowNoBasket");
            }

        }

        public ActionResult ShowNoBasket()
        {

            return View();
        }

        [HttpGet]
        public ActionResult AddBasketItem(int productId)
        {

            Customer customer = _sessionHelper.Get<Customer>();
            _basketManager.AddBasketItem(productId, customer.CustomerId);

            return RedirectToAction("Index", "Product");
        }

        [HttpGet]
        public ActionResult DeleteBasketItem(int productId)
        {

            Customer customer = _sessionHelper.Get<Customer>();
            _basketManager.DeleteBasketItem(productId, customer.CustomerId);

            return RedirectToAction("MyBasket", "Basket", new { });
        }

        [HttpGet]
        public ActionResult IncreaseBasketItem(int productId)
        {
            Customer customer = _sessionHelper.Get<Customer>();

            _basketManager.IncreaseBasketItem(customer.CustomerId, productId);

            return RedirectToAction("MyBasket", "Basket");

        }

        [HttpGet]
        public ActionResult DecreaseBasketItem(int productId)
        {

            Customer customer = _sessionHelper.Get<Customer>();
            _basketManager.DecreaseBasketItem(customer.CustomerId, productId);

            return RedirectToAction("MyBasket", "Basket");
        }
    }
}

XYZ.WebPage/XYZ.Client/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using XYZ.Business.Abstraction;
using XYZ.Business.Implamentation;
using XYZ.Client.Helper.Abstraction;
using XYZ.Client.Helper.Implamentation;
using XYZ.Entities;


namespace XYZ.Client.Controllers
{
    [LogInFilter]
    public class OrderController : Controller
    {
        private readonly IOrderManager _orderManager;
        private readonly IShipperManager _shipperManager;
        private readonly ISessionHelper _sessionHelper;

        public OrderController()
        {
            _sessionHelper = DependencyInjectionModule.Resolve<ISessionHelper>();
            _orderManager = DependencyInjectionModule.Resolve<IOrderManager>();
            _shipperManager = DependencyInjectionModule.Resolve<IShipperManager>();
        }
        public ActionResult OrderBasket()
        {
            ViewBag.data = _shipperManager.GetShippers();

            return View();
        }

        public ActionResult OrderBasketPost(Order order)
        {
            Customer customer = _sessionHelper.Get<Customer>();
            _orderManager.CreateOrder(customer.CustomerId, order);
            return RedirectToAction("PayOrder", "OrderPayment");
        }
    }
}

XYZ.WebPage/XYZ.Client/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using XYZ.Business.Abstraction;
using XYZ.Business.Implamentation;
using XYZ.Client.Helper.Implamentation;
using XYZ.Client.Models;
using XYZ.Entities;

namespace XYZ.Client.Controllers
{
    [LogInFilter]
    public class ProductController : Controller
    {
        private readonly IProductManager _productManager;
        public const int PageSize = 2;
        public ProductController()
        {
            _productManager = DependencyInjectionModule.Resolve<IProductManager>();
        }

        public ActionResult Index(int currentPageIndex = 1)
        {
            return View(this.GetProducts(currentPageIndex));
        }

        public PagingModel GetProducts(int currentPage = 1)
        {
            int maxRows = 40;


            List<Product> products = _productManager.GetProducts();
            PagingModel model = new PagingModel();

            model.Product = (from product in products
                             select product)
                .OrderBy(r => r.ProductId)
                .Skip((currentPage - 1) * maxRows)
                .Take(maxRows).ToList();

            double pageCount = (double)((decimal)products.Count() / Convert.ToDecimal(maxRows));
            model.PageCount = (int)Math.Ceiling(pageCount);

            model.CurrentPageIndex = currentPage;

            return model;
        }

        public PartialViewResult Search(string q)
        {

            List<Product> products = _productManager.GetProducts();

            if (q.IsNullOrWhiteSpace())
            {
                var search = products.Where(r => r.Name.Contains(q) ||
                                                 String.IsNullOrEmpty(q)).Take(100);
                return PartialView("ProductSearchResults", search);
            }
            else
            {
                if (q.Substring(0, 1).Equals(q.Substring(0, 1).ToUpper()))
                {
                    string secondVersion = q.Substring(0, 1);
                    secondVersion = secondVersion.ToLower();
                    secondVersion = secondVersion + q.Substring(1);
                    var search = products.Where(r => r.Name.Contains(q) || r.Name.Contains(secondVersion) ||
                                                     String.IsNullOrEmpty(q)).Take(100);

                    return PartialView("ProductSearchResults", search);
                }
                else
                {
                    string secondVersion = q.Substring(0, 1);
                    secondVersion = secondVersion.ToUpper();
                    secondVersion = secondVersion + q.Substring(1);
                    var search = products.Where(r => r.Name.Contains(q) || r.Name.Contains(secondVersion) ||
                                                     String.IsNullOrEmpty(q)).Take(100);

                    return PartialView("ProductSearchResults", search);
                }

            }

        }

    }
}

XYZ.WebPage/XYZ.Client/Views/Basket/DeleteBasketItem.cshtml
@model XYZ.Entities.Product

@{
    ViewBag.Title = "DeleteBasketItem";
}

<h2>DeleteBasketItem</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Barcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Barcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Delete", "Index", "Product", new{},null})
        </div>
    }
</div>

XYZ.WebPage/XYZ.Client/Views/Basket/MyBasket.cshtml
@model XYZ.Entities.Basket

@{
    ViewBag.Title = "MyBasket";
}

<h2>MyBasket</h2>

<div>
    <h4>Basket</h4>
    
    @Html.ActionLink("Hurry Up!! Get an Order ;)", "OrderBasket", "Order", new {}, null)
    <hr>
    @Html.ActionLink("Back to Products", "Index", "Product", new {}, null)
    <body>
        <table class="table">
            <tr>
                <th class="col-sm-3">
                    Barcode
                </th>
                <th class="col-sm-3">
                    Name
                </th>
                <th class="col-sm-3">
                    Price
                </th>
                <th class="col-sm-3">
                    Qty
                </th>

            </tr>


            @foreach (var item in Model.BasketItemProducts)
            {
                <tr>
                    <td>
                        @item.Product.Barcode
                    </td>
                    <td>
                        @item.Product.Name
                    </td>
                    <td>
                        @item.Product.Price
                    </td>
                    <td>
                        @item.BasketItem.Qty
                    </td>
                    <td>
                        @Html.ActionLink("-", "DecreaseBasketItem", "Basket", new { productId = item.Product.ProductId }, null)
                        @Html.ActionLink("+", "IncreaseBasketItem", "Basket", new { productId = item.Product.ProductId }, null)
                        @Html.ActionLink("Delete", "DeleteBasketItem", "Basket", new { productId = item.Product.ProductId }, null)

                    </td>
                </tr>
            }

        </table>
    </body>

</div>







XYZ.WebPage/XYZ.Client/Views/Basket/ShowNoBasket.cshtml
@using XYZ.Client.Helper.Implamentation

@{
    ViewBag.Title = "ShowNoBasket";
}

<h2>:( Your cart ..</h2>



<table class="table">
   Your cart is empty. @Html.ActionLink(" Go for trendy !! ", "Index", "Product", new { }, null)

</table>
